services:
  backend:
    image: eclipse-temurin:21-jdk-jammy
    container_name: gaptrip-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.m2:/root/.m2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gaptrip_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    command: ./mvnw spring-boot:run
    tty: true

  frontend:
    image: node:20-bullseye
    container_name: gaptrip-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev"
    tty: true

  db:
    image: mysql:8.0
    container_name: gaptrip-db
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: gaptrip_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: